# Generated by Django 6.1.1 on 2026-09-24 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewai', '0002_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Aptitude', 'Aptitude'), ('HR', 'HR'), ('Coding', 'Coding'), ('Database', 'Database'), ('Web Development', 'Web Development'), ('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('Other', 'Other')], default='Technical', max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20)),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='interview',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviewai.interview')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='interviewai.question')),
            ],
            options={
                'ordering': ['question_number'],
                'unique_together': {('interview', 'question'), ('interview', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, default='', max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks', models.FloatField(default=0)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('interview_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interviewai.interviewquestion')),
            ],
        ),
    ]
